### PR TITLE
feat: add nftmint, nftmarket document

### PR DESCRIPTION
**Pull request by hikaruNagamine**
- Added CLI documentation for developers
  - nftmint
  - nftmarket

### CODE REVIEW

**Comment by taiki1frsy** [comment]
Some `UnUnifi` there.
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/cli-introduction.md?plain=1#L3
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/cli-introduction.md?plain=1#L20
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/cli-introduction.md?plain=1#L24

**Comment by taiki1frsy** [comment]
Why don't we put a public endpoint info in  this section?
`https://a.lcd.ununifi.cauchye.net:443` is available.
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/cli-introduction.md?plain=1#L22

**Comment by taiki1frsy** [comment]
I think it's better to have brief descriptions for each module in this section like the Description in each page.
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/modules/README.md?plain=1#L5

**Comment by taiki1frsy** [comment]
About the queries in nftmint, the `Usage` description in terminal was not complete.
So I modified them in `newDevelop` branch.
Please install that binary and refer to them again?
https://github.com/UnUniFi/chain/tree/newDevelop

**Comment by taiki1frsy** [comment]
I think the Flags which are common for all of the command aren't necessary to be written in all command.
How about just put common Flags in one section for query and tx and remove them from each command after that?

**Comment by taiki1frsy** [comment]
`nfsmarket` -> `nftmarket`
https://github.com/UnUniFi/gitbook/blob/82ac66e8e7665e02f8ba279c018f24e568808fde/cli/modules/nftmarket.md?plain=1#L3

**Comment by hikaruNagamine** [comment]
@taiki1frsy 
I have reviewed the comments and made a revised commit.
Please review.

**Comment by taiki1frsy** [comment]
There's inappropriate flags in mint-nft tx because of my implementation.
So I fixed it at https://github.com/UnUniFi/gitbook/pull/23/commits/e2024006f3c88723ae812fb4efe42f941be3e7a9.

**Review by taiki1frsy — APPROVED** [review]

**Pull request merged**
