### PR TITLE
Update ununifid-installation-and-setup.md

### PR DESCRIPTION
**Pull request by glukoss2021**
# Description

### Corresponding Issue
**Issue number** - #3 

## Entry to the community program
**Discord-userId** - `Aleksei#7906`
**UnUniFi-walletAddress** - `ununifi1ydtts8a9r5jr0qmls9cy60p2j9ewvg6mrnkh4z`

### Author Checklist
- [x] Checked Contribute guide line document
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] entered the necessary information for the community program

### Reviewers Checklist
- [ ] confirmed the content is effective

### CODE REVIEW

**Comment by taikiFurusyo** [comment]
Thank you for putting PR, @glukoss2021 .
Could you fill the PR template content above to be qualified as a participant of community program?

**Comment by taikiFurusyo** [comment]
@hikaruNagamine 
Could you review this PR?

**Comment by glukoss2021** [comment]
Should I fill Author Checklist? Discord nick and wallet - done

**Comment by taikiFurusyo** [comment]
> Should I fill Author Checklist? Discord nick and wallet - done

@glukoss2021 yes, please.
Thank you for the cooperation.

**Comment by glukoss2021** [comment]
@taikiFurusyo check please

**Comment by taikiFurusyo** [comment]
>  check please
To @glukoss2021 , the necessary info are filled now.
Thank you for the cooperation.

**Comment by taikiFurusyo** [comment]
> I need to close PR or you do it?

No, we review ur work. Once it's approved, we close.
Please wait.

**Comment by glukoss2021** [comment]
Ok, no problem) Thx

**Pull request closed without merging**
